-- -- 코드를 입력하세요
SELECT C.CAR_ID
     , C.CAR_TYPE
     , C.DAILY_FEE * (100 - P.DISCOUNT_RATE) * 30 / 100 FEE
  FROM CAR_RENTAL_COMPANY_CAR C
     , CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
 WHERE CAR_ID NOT IN (SELECT DISTINCT CAR_ID 
                        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                       WHERE END_DATE >= TO_DATE('2022-11-01', 'yyyy-mm-dd')
                         AND START_DATE <= TO_DATE('2022-11-30', 'yyyy-mm-dd'))
   AND C.CAR_TYPE IN ('세단', 'SUV')
   AND C.CAR_TYPE = P.CAR_TYPE(+)
   AND P.DURATION_TYPE = '30일 이상'
   AND C.DAILY_FEE * (100 - P.DISCOUNT_RATE) * 30 / 100 BETWEEN 500000 AND 2000000
 ORDER BY 3 DESC, 2, 1 DESC