SELECT TO_NUMBER(TO_CHAR(START_DATE, 'MM')) MONTH
     , A.CAR_ID
     , COUNT(*) RECORDS
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
     , ( SELECT CAR_ID
           FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
          WHERE TO_CHAR(START_DATE, 'YYYY-MM') BETWEEN '2022-08' AND '2022-10'
         HAVING COUNT(*) >= 5
          GROUP BY CAR_ID) B
 WHERE A.CAR_ID = B.CAR_ID
   AND TO_CHAR(A.START_DATE, 'YYYY-MM') BETWEEN '2022-08' AND '2022-10'
 GROUP BY TO_CHAR(START_DATE, 'MM'), A.CAR_ID
 ORDER BY 1,2 DESC