-- 코드를 입력하세요
SET @HOUR = -1;

SELECT A.HOUR
     , COALESCE(B.COUNT, 0) COUNT
  FROM ( SELECT (@HOUR := @HOUR +1) HOUR
           FROM ANIMAL_OUTS
          WHERE @HOUR < 23
       ) A
  LEFT JOIN
       ( SELECT DATE_FORMAT(DATETIME, '%H') HOUR
              , COUNT(*) COUNT FROM ANIMAL_OUTS
          GROUP BY DATE_FORMAT(DATETIME, '%H')
          ORDER BY HOUR
       ) B ON A.HOUR = B.HOUR