-- 코드를 입력하세요
SELECT USER_ID
     , NICKNAME
     , TOTAL_SALES
  FROM USED_GOODS_USER U 
  LEFT JOIN (SELECT WRITER_ID
                  , SUM(PRICE) TOTAL_SALES
               FROM USED_GOODS_BOARD
              WHERE STATUS = 'DONE'
              GROUP BY WRITER_ID) B
    ON USER_ID = WRITER_ID
 WHERE TOTAL_SALES >= 700000
 ORDER BY TOTAL_SALES