-- 코드를 입력하세요
SELECT M.MEMBER_NAME
     , R.REVIEW_TEXT
     , TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') REVIEW_DATE
  FROM REST_REVIEW R
  JOIN MEMBER_PROFILE M ON R.MEMBER_ID = M.MEMBER_ID
  JOIN (SELECT MEMBER_ID
          FROM REST_REVIEW
        HAVING COUNT(*) = (SELECT MAX(COUNT(*))
                             FROM REST_REVIEW
                            GROUP BY MEMBER_ID)
         GROUP BY MEMBER_ID) GR ON R.MEMBER_ID = GR.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT