-- 코드를 입력하세요
SELECT H.CAR_ID
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
  JOIN CAR_RENTAL_COMPANY_CAR C
    ON H.CAR_ID = C.CAR_ID
 WHERE TO_CHAR(START_DATE, 'MM') = '10'
   AND CAR_TYPE = '세단'
 GROUP BY H.CAR_ID
 ORDER BY H.CAR_ID DESC